apply plugin: 'com.android.application'
android {
    compileSdk 36
    defaultConfig {
        applicationId "com.prefix_infix_postfix_converter.prefix_infix_postfix_converter"
        minSdk 24
        targetSdk 36
        versionCode 19
        versionName "2.8"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    namespace 'com.example.prefix_infix_postfix_converter'
}
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.0'
    implementation 'androidx.core:core-splashscreen:1.2.0'

    implementation 'com.github.hotchemi:android-rate:1.0.1'
    implementation 'com.google.android.gms:play-services-ads:23.6.0'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}